name: Build, Publish and Deploy

on:
  push:
    branches: [main, master]
  # Allow manual triggering from the GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: write

# Allow only one concurrent deployment
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com"
          scope: "@heldtogether"

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build Package
        run: npm run build

      - name: Set up Package Version
        run: |
          # Extract version from package.json and update package name to include org scope if needed
          VERSION=$(node -p "require('./package.json').version")
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          # If package name doesn't include the scope, add it
          if [[ "$PACKAGE_NAME" != @* ]]; then
            npm pkg set name="@${{ github.repository_owner }}/$PACKAGE_NAME"
          fi

          # If version is 0.0.0, use a timestamp-based version
          if [[ "$VERSION" == "0.0.0" ]]; then
            TIMESTAMP=$(date +%Y%m%d%H%M%S)
            npm version "0.0.0-${TIMESTAMP}" --no-git-tag-version
          fi

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-storybook:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./storybook-static"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
